//
// Generated file, do not edit! Created by nedtool 5.2 from src/PacketRequestMessage.msg.
//

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#ifndef __PACKETREQUESTMESSAGE_M_H
#define __PACKETREQUESTMESSAGE_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0502
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
#include "veins/modules/messages/WaveShortMessage_m.h"
// }}

/**
 * Class generated from <tt>src/PacketRequestMessage.msg:26</tt> by nedtool.
 * <pre>
 * packet PacketRequestMessage extends WaveShortMessage
 * {
 *     string packetId;
 *     int segNum;
 * }
 * </pre>
 */
class PacketRequestMessage : public ::WaveShortMessage
{
  protected:
    ::omnetpp::opp_string packetId;
    int segNum;

  private:
    void copy(const PacketRequestMessage& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const PacketRequestMessage&);

  public:
    PacketRequestMessage(const char *name=nullptr, short kind=0);
    PacketRequestMessage(const PacketRequestMessage& other);
    virtual ~PacketRequestMessage();
    PacketRequestMessage& operator=(const PacketRequestMessage& other);
    virtual PacketRequestMessage *dup() const override {return new PacketRequestMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual const char * getPacketId() const;
    virtual void setPacketId(const char * packetId);
    virtual int getSegNum() const;
    virtual void setSegNum(int segNum);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const PacketRequestMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, PacketRequestMessage& obj) {obj.parsimUnpack(b);}


#endif // ifndef __PACKETREQUESTMESSAGE_M_H

